@startuml first

class carrito(){
    def __init__(self):
        self.color
        self.marca
        self.num_puertas
        self.tipo
    
    def moverse():
        print("El coche se mueve")
    
    def pitar():
        print("El coche hace miau")

    def acelerar():
        print("El coche hace BRUM BRUM")
    
    def atropellar():
        print("El coche ha atropellado a alguien")
    
    def reversa():
        print("El coche está en reversa")
}

class perro(){

}

class juan(){
    
}

@enduml